### ISSUE TITLE
Login de Usuário [oAuth]

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#11]
## Requisitos
Autenticação através de oAuth, utilizando plataformas conhecidas como Google, LinkedIn e Facebook.
Tendo em vista o aumento de mídias sociais no mundo e a quantidade de contas criadas em diversas plataformas, os usuários acabam esquecendo seus diversos acessos e esta é mais uma forma de entregarmos uma experiência positiva aos usuários.

*User Story*
**US002**: Como usuário, gostaria de me conectar à plataforma de forma rápida, utilizando minha conta Google existente, para não precisar de mais uma conta com senha diferente.  

**Critérios de Aceitação**
- O usuário deve autorizar o acesso da plataforma as suas informações da plataforma de terceiros. [LGPD]
- O usuário poderá converter a conta oAuth para uma conta Padrão com Usuário e Senha da plataforma.

**Impacto se não desenvolvida**
Mínimo

**Proporção**
Acreditamos que 20% dos usuários serão beneficiados através do acesso OAuth2

**Objetivo**
Facilitar o acesso dos usuários à plataforma.

**Evidência**
temos vários casos de clientes que "não tem uma conta de e-mail" somente a conta da Clínica ou Laboratório.

**Ideias**
Seria interessante "forçar" a criação de um novo e-mail no Google por exemplo para que esse usuário não misture acesso Pessoa Jurídica com Pessoa Física.

**Urgência**
Média, seria interessante ter na plataforma.

## Especificação Técnica
Falta especificação

## Design

![Login](https://user-images.githubusercontent.com/63128934/79468282-1e387700-7fd5-11ea-80fd-e81743075a26.png)

## To-do

 - [ ] Login via oAuth2 (Google)
 - [ ] Login via oAuth2 (LinkedIn)
 - [ ] Login via 0Auth2 (Facebook)
