### ISSUE TITLE
O Menu dinâmico

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#131]
**Descreva a Tarefa**
O menu principal deve apresentar ou esconder secções/opções de acordo com os dados do usuário.

- É colaborador de alguma Clínica? Exibir secção/opções para Clínica.
- É um colaborador de algum Laboratório? Exibir secção/opções para Laboratório.
- É um veterinário ? Exibir opções de uso exclusivo dos veterinários.

### Todo
- [ ] Carregar estas informações após o login. 
- [ ] O Menu deve ser construído dinamicamente.
- [ ] Devemos impedir que o usuário navegue através da URL à secções/opções ocultas no menu.
