### ISSUE TITLE
Adicionar colunas de "ultima atividade", "status da conta" e "conta verificada"

### ISSUE THREAD

**Issue by Deullam** [Hubvet8/hubvet-web#133]
**Descreva a Tarefa**

Adicionar colunas e campos no perfil de usuário

### Todo
- [ ] Adicionar Coluna "ultima atividade"
- [ ] Adicionar status da conta
- [ ] Adicionar conta verificada

**Comment by PCiranda** [comment]
Vamos precisar de uma coluna `verificado`na tabela de usuário, semelhante ao que já temos para e-mail, endereço e telefone.
