### ISSUE TITLE
Botão de Manter Logado

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#135]
Implementar a funcionalidade do botão "Manter-me logado" 

### Todo
- [ ] Ouvir evento "beforeunload" caso "manter-me logado" seja `false`.
- [ ] Disparar requisição para API para revogar o token atual.
- [ ] Limpar Auth e Usuário do localStorage.  

### Observações:
- O 'beforeunload' é emitido para cada aba fechada no navegado ? se sim precisamos executar o logout somente quando a última aba for fechada. Uma possibilidade é tentar rastrear quantas "abas" o usuário abriu, armazenando essa informação no próprio localstorage.
