### ISSUE TITLE
[ÉPICO] Correções em Wizard de Laboratório

### ISSUE THREAD

**Issue by johhny0** [Hubvet8/hubvet-web#169]
## Descrição
Correções necessárias em Wizard de Laboratório.

- [ ] Adicionar validação em todos os campos
- [ ] Ajustes de Layout
- [ ] Fazer post com os dados para o servidor
