### ISSUE TITLE
Listagem/Cadastro de Exames

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#17]
## Motivação
Módulo de cadastro de Exames necessário para operacionalização do ambiente de Laboratórios com as Clínicas/Médicos Veterinário.

*User Story*: 
US001: Como *administrador do laboratório* desejo pode realizar *o cadastro, exclusão, edição e desativação de exames* para *fornecer uma lista de exames para meus clientes requisitarem*.  
US002: Como *operador da clínica* desejo poder realizar *o repasse do custo desses exames com a margem de lucro da clínica* para *que o processo possa ser integrado e transparente para o cliente final*.

**Impacto se não desenvolvermos...** 
Inviabiliza o propósito da Plataforma

**Proporção** 
100% dos usuários administradores de Laboratório.
100% dos clientes do Laboratório.

**Objetivo** 
Proporcionar um cadastro de exames para cada ambiente laboratorial.

**Evidência** 
Necessidade cadastral das informações pra operacionalização.

**Ideias** 
Disponibilizarmos uma base de Exames padrão do mercado laboratorial para SETUP inicial.

## Critérios de Aceitação 
CRUD funcional

## Especificação Técnica
*Descreva aqui tecnicamente como esta requisição pode ser resolvida! [Ex: Código de exemplo]*

## Design

**Listagem**
![image.png](https://images.zenhubusercontent.com/5e9a31126a44049a3a9b9e85/492e360a-b3b6-49bd-a73f-fb4efb9c1d97)

**Cadastro**
![image.png](https://images.zenhubusercontent.com/5e9a31126a44049a3a9b9e85/a9a8a12d-ab94-4180-b3e9-66851036f63f)

## To-do 

**Processo Completo**
- [x] Criar Issue
- [x] Criar Design/Layout
- [ ] Criar novo Branch e Pull-request para essa issue
- [ ] Criar um template o mais fiel possível ao Design com o Vuetify
- [ ] Implementar as funcionalidades da view/componente e outras camadas de serviço
- [ ] Review do código [Frontend/Backend]
- [ ] Review do Design e UI/UX
- [ ] Liberar Issue para merge
