### ISSUE TITLE
Cadastro de Animal

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#18]
## Motivação
O animal é nossa entidade principal dentro da plataforma, e para tal precisamos ter um cadastro único desse animal, pois todas as entidades utilizam seus dados para prestação de serviços. 

*User Story*: 
US001: Como *proprietário* desejo pode realizar *o cadastro dos meus animais* para *controlar as informações do meu animal e decidir quais funcionalidades utilizar*.
US002: Como *recepcionista da Clínica* desejo pode realizar *o cadastro dos pacientes* para *conectar o paciente/proprietário aos nossos serviços*.  

**Impacto se não desenvolvermos...** 
Não conseguiremos ter um controle sobre o animal e co-relacionar serviços ao mesmo.

**Proporção** 
100% dos envolvidos na plataforma desde proprietário até o Laboratório veterinário.

**Objetivo** 
Cadastrar o animal para centralizar as informação na plataforma e conectar entidades/atores.

**Evidência** 
Hoje não existe controle algum dos animais, seja no âmbito as Clínicas, Laboratórios ou até mesmo no controle do animal pelo proprietário. 

**Ideias** 
Dashboard do animal
Exemplo feito para Crianças
![a2848960434093 5a4d090c41927](https://user-images.githubusercontent.com/63128934/79506935-34fac000-800d-11ea-815e-ce30608f0ab5.png)

## Critérios de Aceitação 
O sistema deve ter um controle padrão de RGA (Registro Geral de Animal) e opção para armazenamento do Chip_id (Pesquisar como funciona para animais chipados)

## Especificação Técnica
*Descreva aqui tecnicamente como esta requisição pode ser resolvida! [Ex: Código de exemplo]*

## To-do 

- [ ] Especificação Técnica 
- [ ] Design
- [ ] Implementação

**Comment by PCiranda** [comment]
@wifzw , Vamos começar com essas.
 
- [ ] View: Meus animais
- [ ] Components/
  - [ ] components/animal/lista.vue
  - [ ] components/animal/formulario-de-cadastro.vue
  - [ ] components/animal/modal-de-cadastro.vue

**Comment by PCiranda** [comment]
Vou preparar um branch para ti e nos falamos na call.
