### ISSUE TITLE
[Tarefa] Tela de Lista (CRUD de Parâmetros)

### ISSUE THREAD

**Issue by wifzw** [Hubvet8/hubvet-web#209]
## Descrição
 - Deve ser feito o cadastro dos parâmetros dos exames para serem utilizados no layout de cadastro de exames

Dados |  Tipo
----|----
id_Parametros_Exame | Int
Nome | String
Unidade | String

## Ações
- Selecionar
  - Deve aparecer o toolbar com a quantidade de itens selecionados e um botão para excluir todos os selecionados
- Editar: 
  - Deve chamar o modal/dialog para editar o Exame OBS: fazer após tela de cadastro estar concluída
- Excluir:
  - Deve excluir o exame da mesma linha
- Pesquisa:
  - Filtros sigla ou nome
 
- [ ] Dados 
- [ ] Botões novo Exame e importar
- [ ] Ações/Métodos
  - [ ] Selecionar: Deve aparecer o toolbar com a quantidade de itens selecionados e um botão para 
  - [ ] excluir todos os selecionados
  - [ ] Editar: Deve chamar o modal/dialog para editar o Exame OBS: fazer após tela de cadastro estar concluída
  - [ ] Excluir: Deve excluir o exame da mesma linha
- [ ] Botão Novo Exame: Deve abrir o modal para cadastrar novo Exame
- [ ] Botão importar :  Deve Abrir uma tela para escolher exames para importar exames
- [ ] Pesquisa:
  - [ ] Pesquisar por sigla ou nome do exame

Sugestões:

Layout:![Inclusão de Parâmetros do Layout v1.png](https://images.zenhubusercontent.com/5eecec81644d09d12fe89b16/807aa25e-bf3e-4793-b3b1-27cd337b2102)

### API da tarefa
Link: 

##Todo
- [ ] Cadastro para exames (Padrão)
- [ ] Inclusão rápida (Na tela de exame)
