### ISSUE TITLE
Listagem/Cadastro de Perfis

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#26]
## Motivação
Agrupamento de exames e diminuição considerável no tempo de  montagem da requisição de exames.

*User Story*: 
**US001:** Como ***administrador do Laboratório*** desejo poder realizar ***o cadastro de grupos de exames, chamados perfis*** para ***oferecer para os clientes selecionarem na requisição de exames os perfis como se fossem uma bateria de exames a um preço diferenciado***.

**US002:** Como ***Médico Veterinário*** desejo poder ***requisitar uma bateria de exames*** para ***não perder tempo procurando exames corriqueiros***.  

**Impacto se não desenvolvermos...** 
Não estaremos construindo a aplicação de forma compatível ao comportamento do mercado veterinário.  

**Proporção** 
100% dos usuários de Clinicas Veterinárias

**Objetivo** 
Proporcionar uma interface para cadastro de Perfis, informações estas que serão utilizadas na requisição de exames.

**Evidência** 
*(Quais as evidênicas reais para esta necessidade? [Casos de Uso])*

**Ideias** 
*(Se possível traga ideias para uma possível solução do problema)*

## Critérios de Aceitação 
*Descreva aqui os requisitos não funcionais, ou seja, que evolvem arquitetura da informação ou regras de negócio!*

## Especificação Técnica
*Descreva aqui tecnicamente como esta requisição pode ser resolvida! [Ex: Código de exemplo]*

## Design

**Listagem**
![image.png](https://images.zenhubusercontent.com/5e9a31126a44049a3a9b9e85/6efcb391-c31e-428d-81af-b175f584b9f7)

**Cadastro**
![image.png](https://images.zenhubusercontent.com/5e9a31126a44049a3a9b9e85/26f065b0-b2e1-45c4-96c1-d6707e02fbca)

## To-do 
*Este é um Checklist de todo processo a ser executado por etapas/itens!*

**Processo Completo**
- [x] Criar Issue
- [x] Criar Design/Layout
- [ ] Criar novo Branch e Pull-request para essa issue
- [ ] Criar um template o mais fiel possível ao Design com o Vuetify
- [ ] Implementar as funcionalidades da view/componente e outras camadas de serviço
- [ ] Review do código [Frontend/Backend]
- [ ] Review do Design e UI/UX
- [ ] Liberar Issue para merge
