### ISSUE TITLE
Cadastro de Materiais

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#29]
*Deve ser simples e direto ao ponto*
*Descreve o problema que está sendo resolvido*
*Propõe uma solução específica*
*Fornece contexto sobre como e por que a solução será usada*
*Links para exemplos relevantes de contexto e trabalho existente*

## Motivação
Reduzir o custo operacional em 80%

*User Story*: Como ***Administrador do Laboratório*** desejo poder realizar ***o cadastro dos materiais*** para ***disponibilizar para os clientes requisitarem Online***..  

**Se não desenvolvermos...** 
*(Qual seria o impacto?)*

**Proporção** 
*(Qual a quantidade ou % de usuários que iremos atingir?)*

**Objetivo** 
*(Seja específico e sucinto!)*

**Evidência** 
*(Quais as evidênicas reais para esta necessidade? [Casos de Uso])*

**Ideias** 
*(Se possível traga ideias para uma possível solução do problema)*

## Critérios de Aceitação 
*Descreva aqui os requisitos não funcionais, ou seja, que evolvem arquitetura da informação ou regras de negócio!*

- [ ] Critério a ser verificado 01
- [ ] Critério a ser verificado 02

## Especificação Técnica
*Descreva aqui tecnicamente como esta requisição pode ser resolvida! [Ex: Código de exemplo]*

## Design
*Insira uma imagem/layout ou wireframe que passe uma ideia visual da funcionalidade! [Ex: Layout ou Print de Exemplo]*
*Cole o Link compartilhado do Design caso existe*

## To-do 
*Este é um Checklist de todo processo a ser executado por etapas/itens!*

- [ ] Call para definição/alinhamento
- [ ] Especificação 
- [ ] Design
- [ ] Implementação
- [ ] Testes Q&A
- [ ] Deploy

----------------------------------

## Definição de done
*Descreva neste espaço qual seria a definição de Pronto nesta Issue*

**Comment by Deullam** [comment]
Criar Tarefa de layout
