### ISSUE TITLE
Módulos Comuns entre Organizações

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#37]
## Descrição
No Ambiente das organizações deverá conter módulos que sejam compartilhados entre as mesmas. 
Exemplos: 
- Solicitação de Exames
- Visualização de Exames
- Acesso a Tabela/Grade de Preços

Devemos pensar em todo o processo sempre envolvendo três visões
1. Clínica/Médico Veterinário
2. Laboratório
3. Proprietário

## Iniciativa / objetivo
Este ambiente compartilhado é o principal objetivo da plataforma. Tendo em vista que hoje os processos são quebrados e Laboratórios "adaptam" sistemas antigos ou de humanas para o ramo veterinário.

### Hipótese
Qual é a sua hipótese sobre o sucesso desta epopeia? Descreva como o sucesso será medido e quais indicadores principais a equipe precisará saber se o sucesso foi atingido.
100% das Clínicas cadastradas utilizando a plataforma para se relacionar com os Laboratórios. Hoje muitas Clínicas ainda utilizam papel por não terem o hábito digital. Teremos que fazer um trabalho de marketing para disseminar as funcionalidades utilizando gatilhos mentais.

KPI01: % de Utilização (Clínicas por Laboratório) 

## Critérios de aceitação e deve ter escopo(Alvo)
Defina o que é essencial para o lançamento e escopo. Mantenha esta seção fluida e dinâmica até obter a prioridade durante o planejamento.

- [ ] Ambientes distintos para Clínicas e Laboratórios.

## Acionistas/Stakeholders
- Sócios da Hubvet
- Clientes de Laboratório

## Linha do tempo
Precisamos dos módulos comuns disponíveis até final de junho/2020. Podemos ter contratempos quanto aos valores de referência que necessitam de estudos e são inerentes ao meio Laboratorial.

## Definição de Feito [DoD]
*Definition of Done:* Descreva abaixo detalhadamente todos os requisitos necessários para que esse Epic seja considerado como **DONE**.

- [ ] Módulo de Atendimento (No Mínimo)
  - [x] Solicitação/Novo Atendimento
  - [ ] Processamento
  - [ ] Inserção de Resultados
  - [ ] Faturamento
- [ ] Visualização de Resultados
- [ ] Impressão de Laudos
