### ISSUE TITLE
Cadastro de Clínicas

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#4]
### Objetivo
Criar uma tela que permita o cadastro de Clínicas.

### Requisição
```js
// POST api/clinicas/
{
    avatar: 'http://hubvet.com.br/avatar.jpg',
    nome: 'Clínica Hubvet',
    razao: 'Clínica  Hubvet ltda.',
    cnpj: '01234567891234',
    endereco: 'Rua xyz'
}
```
### Respostas
Sucesso retornará somente `true`
Falhas retornarão as msgs definidas no `validator`.

### Design
![Setup - Cad Clínica  Dados Básicos](https://user-images.githubusercontent.com/63128934/79039529-36b12780-7bb8-11ea-8c90-0d36299d9693.png)
Referênica de Design: https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=0%3A1
O responsável pela Clínica. que normalmente é um médico veterinário, trará os dados do usuário da sessão, caso seja outra pessoa, o usuário poderá cadastrar através de um botão "Adicionar outro Responsável +" na listagem. O sistema deverá carregar o responsável automaticamente.

![Listagem de Clínicas](https://user-images.githubusercontent.com/63128934/79091176-ae02ca80-7d22-11ea-8eff-c1c26fccde7c.png)
Nota: Fiz a listagem de clínicas respeitando as limitações do Vuetify.

### Todo

- [ ] Especificação da Api
  - [ ] Definir formato da Requisição
  - [x] Definir formatos das Respostas
- [x] Design (referência)
- [ ] Implementação
- [ ] Validação do Formulário

**Comment by leolands** [comment]
Estou com uma dúvida quanto ao plugin a ser utilizado para o upload das logomarcas, pois o que ocorre frequentemente é cliente subir imagens que não se encaixam ao layour, então imagino em um modal com um CROP fixo de imagem onde o usuário posiciona a logomarca em um retângulo ou de acordo com o espaço disponibilizado para a imagem no sistem.
