### ISSUE TITLE
Planejamento novo site Hubvet.cloud

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#46]
## Descrição
Planejamento do website que deve ser voltado para uma compra guiada.

## Iniciativa / objetivo
Afeta diretamente o time de marketing/comercial para atingimento de metas/conversões de novos clientes pagantes.

### Hipótese
O site deve ser capaz de filtrar os tipos de Leads e guiá-los através do melhor canal. 

## Critérios de aceitação e deve ter escopo(Alvo)
- [ ] Estudo sobre boas práticas de marketing para Plataformas SaaS.
- [ ] Reestruturação do Mapa Metal para passar para equipe executar o Design.
- [ ] Executar o Mapa no Mila Note [Converter do .XMIND]

## Acionistas
Afetará diretamente nas metas de conversão da plataforma.

## Linha do tempo
Pretendemos finalizar este novo website até final de Julho/2020.

## Definição de Feito [DoD]
*Definition of Done:* Descreva abaixo detalhadamente todos os requisitos necessários para que esse Epic seja considerado como **DONE**.

- [ ] Mapa do Site
- [ ] Base de referências
