### ISSUE TITLE
Cadastro de Laboratórios

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#5]
### Objetivo
Criar uma tela que permita o cadastro de Laboratórios.

### Requisição
```js
// POST api/laboratorios/
{
    nome: 'Lab Hubvet',
    razao: 'Lab  Hubvet ltda.',
    cnpj: '01234567891234',
    endereco: {
        cep: '12345333',
        logradouro: 'Rua x',
        numero: '123',
        complemento: 'casa b',
        bairro: 'Bairro Y',
        municipio: 'municipio Z',
        uf : 'SC'
    },
    telefone: {
        ddd:21,
        numero:987654321
    },
    arquivo: file
}
```
### Respostas
Sucesso retornará somente `true`
Falhas retornarão as msgs definidas no `validator`.

### Design
![Setup - Cad Lab  Dados Básicos](https://user-images.githubusercontent.com/63128934/79039562-62cca880-7bb8-11ea-8d90-c368df5b95e5.png)
Referênica de Design: https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=0%3A1

### Todo

- [X] Especificação da Api
  - [X] Definir formato da Requisição
  - [x] Definir formatos das Respostas
- [x] Design (referência)
- [ ] Implementação
- [ ] Validação do Formulário

### Dúvidas
Existe a necessidade e extrair o `endereço`,`telefone` e `documentos`? 
R: Não, apenas buscar o endereço com base no CEP inserido.

**Comment by leolands** [comment]
Segue referênica de Design: https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=0%3A1

Nota: Creio que seja interessante desenharmos uns Casos de Uso pra que eu possa ter um direcionamento no design.

**Comment by PCiranda** [comment]
@leolands ,
Vou adicionar a informação lá em cima.

**Comment by leolands** [comment]
![image](https://user-images.githubusercontent.com/63128934/78910073-c4770080-7a5a-11ea-9de9-811d87c1447a.png)
Imaginei alguma coisa nesse sentido quando o usuário entra pela primeira vez na plataforma....

**Comment by johhny0** [comment]
```
...,
telefone: {
        ddd:21,
        numero:987654321
    },
    arquivo: file
```

O campo Arquivo seria o Contrato? 
Digo isso pois nesse caso, seria mais interessante colocar o nome de "contrato".
Não concorda?

**Comment by PCiranda** [comment]
Sim. O nome da coluna na tabela não precisa ser o mesmo que a da requisição .

Uma única requisição transportar os dados,
Laboratório
Endereço
Telefone
Documento

Ou separar em 4 requisições se utilizarmos "passo a passo"

Não necessariamente o requisição precisa ter o formato fiel ao que será armazenado.

**Comment by johhny0** [comment]
Acredito que uma unica requisição seja a melhor forma.
Não serão tantos dados e muitas requisições mesmo que pequenas podem sobrecarregar o servidor

Gostaria de levantar duas questões: 

- Há a necessidade de armazenarmos esse contrato?
- A forma como o telefone foi separado faz sentido no Brasil, mas faz sentido quando o sistema atingir o exterior? Acredito que nele podemos deixar mais simples: 
> telefone: {
>         ddd:21,
>         numero:987654321
>     },
Em:
`telefone: 21987654321`

**Comment by leolands** [comment]
> ```
> ...,
> telefone: {
>        ddd:21,
>        numero:987654321
>    },
>    arquivo: file
> ```
> 
> O campo Arquivo seria o Contrato?
> Digo isso pois nesse caso, seria mais interessante colocar o nome de "contrato".
> Não concorda?

Sim, já atualizei na nova tela.

**Comment by leolands** [comment]
> Acredito que uma unica requisição seja a melhor forma.
> Não serão tantos dados e muitas requisições mesmo que pequenas podem sobrecarregar o servidor
> 
> Gostaria de levantar duas questões:
> 
> * Há a necessidade de armazenarmos esse contrato?
> * A forma como o telefone foi separado faz sentido no Brasil, mas faz sentido quando o sistema atingir o exterior? Acredito que nele podemos deixar mais simples:
> 
> > telefone: {
> > ddd:21,
> > numero:987654321
> > },
> 
> Em:
> `telefone: 21987654321`

1 - Acredito que seja necessário validarmos se o Laboratório é real pra evitarmos fraude e problemas futuros.
2 - Creio  que faça sentido armazenarmos em um padrão, mas pelo que pesquisei, sempre serão três "campos" [Código Internacional] [Código de àrea] [Número do Telefone]
Ex USA: +1 420 8798765
Ex Brasil: +55 49 32241773

**Comment by PCiranda** [comment]
Podemos seguir com o formato E.164 (+5521987654321) e extrair as informações utilizando uma biblioteca.

https://libphonenumber.appspot.com/phonenumberparser?number=%2B5521987654321&geocodingLocale=pt-BR

Parsing Result |--
--|--
country_code | 55
national_number | 21987654321
extension | 
country_code_source | FROM_NUMBER_WITH_PLUS_SIGN
italian_leading_zero | false
raw_input | +5521987654321


Validation | Results
--|--
Result from isPossibleNumber()|true
Result from isValidNumber()|true
Phone Number region|BR
Result from getNumberType()|MOBILE


Formatting | Results
--|--
E164 format|+5521987654321
Original format|+55 21 98765-4321
National format|(21) 98765-4321
International format|+55 21 98765-4321
Out-of-country format from US|011 55 21 98765-4321
Out-of-country format from CH|00 55 21 98765-4321


PhoneNumberOfflineGeocoder | Results
--|--
Location|Rio de Janeiro

PhoneNumberToTimeZonesMapper |Results
--|--
Time Zones| [America/Sao_Paulo]


PhoneNumberToCarrierMapper |Results
--|--
Carrier|Oi

**Comment by leolands** [comment]
@PCiranda e @johhny0 não fiz a listagem de Laboratórios por se tratar da mesma estrutura visual de dados, mudando somente o BD. Qualquer coisa @johhny0 se precisar eu desenho a tela.

**Comment by PCiranda** [comment]
Basta usar a da clínicas como referência. Se trata de uma listagem simples.
