### ISSUE TITLE
Controle de Estoque

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#61]
## Descrição
Em levantamentos com clientes identificamos que os Laboratórios necessitam de um controle de estoque hoje inexistem no Laboratório.
.
US01: Eu como administrador do Laboratório preciso saber como está o estoque de materiais(Tubos) disponibilizados para as Clínicas para economizar recursos financeiro e saber se há desvio de materiais para outras finalidades.

## Iniciativa / objetivo
Esta Funcionalidade está diretamente ligada à Solicitação de Exames, pois, utiliza materiais para coleta de amostras. E tem como objetivo principal controlar o estoque do laboratório para economia de investimentos.

### Hipótese
Qual é a sua hipótese sobre o sucesso desta epopeia? Descreva como o sucesso será medido e quais indicadores principais a equipe precisará saber se o sucesso foi atingido.
Economizarmos pelo meno 30% de custo operacional mensal do Laboratórios. Iremos medir o sucesso desta funcionalidade analisando a quantidade de *materiais disponibilizados* x *materiais utilizados*. 

## Critérios de aceitação e deve ter escopo(Alvo)
Defina o que é essencial para o lançamento e escopo. Mantenha esta seção fluida e dinâmica até obter a prioridade durante o planejamento.
- [ ] Controle de entrada de estoque (Compra)
- [ ] Controle de Utilização de Materiais (Baixa)
- [ ] Controle de Materiais inutilizados (Motivo)

## Acionistas
Não se aplica

## Linha do tempo
Segundo Semestre de 2020.

## Definição de Feito [DoD]
*Definition of Done:* Descreva abaixo detalhadamente todos os requisitos necessários para que esse Epic seja considerado como **DONE**.
- [ ] Satisfazer o controle mínimo do Laboratório
- [ ] Reduzir custos operacionais do Laboratório
- [ ] Inibir ações ilícitas das Clínicas (Ex: Utilizar materiais para solicitar exames de outros Laboratórios)
