### ISSUE TITLE
[ Laboratório ] Lista de Perfis

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#73]
## Objetivo

Está página será o ponto de entrada para o gerenciamento dos Perfis.

## Design
[![Listagem de Perfis](https://user-images.githubusercontent.com/5818309/83406684-89070b80-a3e5-11ea-86ec-3ab986d6bda3.png)
](https://www.figma.com/proto/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=397%3A297&scaling=min-zoom)

### Conteúdo da tabela
Título | Descrição | Filtrável | Classificavel
---|---|---|---
Código | - | Sim | Sim
Nome | - | Sim | Sim
Descrição | - | Sim | Não
Prazo | - | Sim | Sim
Status | - | Sim | Sim 
Ações | - | Não | Não

## TODO

- [ ] O Campo de Pesquisa filtrará o conteúdo apresentado na tabela a baixo.
- [ ] Botão de Cadastro de Exame - será usado posteriormente para apresentar um formulário.
- [ ] Tabela
  - [ ] Paginação - 10, 25 e 50
  - [ ] Ações: Editar, Deletar
