### ISSUE TITLE
[ Laboratório ] Cadastro de Exames

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#74]
## Objetivo

Cadastrar um novo exame na plataforma.

## Design
[![Listagem de Perfis](https://user-images.githubusercontent.com/5818309/83406684-89070b80-a3e5-11ea-86ec-3ab986d6bda3.png)
](https://www.figma.com/proto/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=397%3A297&scaling=min-zoom)

### Formulário
Título | Descrição | Validações 
--------|---------------|---------------
Código | - | `required`, `unique`
Nome | - | `required`
Descrição | - | -
Prazo | - | `required`, `boolean`
Preço | - | `required`, `numeric`, `min:0`
Status | - | `required`, `boolean`

## TODO

- [ ] Abir modal de cadastro ao clicar no botão.
- [ ] Formulário
- [ ] Validações
- [ ] Ao clicar em Cadastrar:
  - [ ] Verifica a Validação do formulário
  - [ ] Muda o estado do formulário para loading = true
  - [ ] Envia a requisição
  - [ ] Se Sucesso:Emite evento, Limpa o Formulário e Fechar modal
  - [ ] Se Falha: Notificar Falha
  - [ ] Muda o estado do formulário loading = false
- [ ] Ao Clicar em Cancelar:
  - [ ]  Limpa o Formulário e Fechar modal

## Observações e Sugestões

- Adicionar um botão de "Cadastrar e adicionar outro" ou um checkbox que possibilite o usuário a permanecer com a modal aberta e adicionar outros exames de maneira contínua.

**Comment by leolands** [comment]
Show. Hoje vou fazer a tela pensando em Cadastro + Modelo.

**Comment by leolands** [comment]
Pensando na adição de sequência de exames vou fazer um modal depois do clique em cadastar com: continuar cadastrando [SIM/NÃO]. Importante isso...

**Comment by leolands** [comment]
Atualizei a Imagem e o Link da tela.
