### ISSUE TITLE
[ Laboratório ] Cadastro de Perfis

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#75]
## Objetivo

Cadastrar um novo Perfil na plataforma.

## Design
[
![Novo Perfil](https://user-images.githubusercontent.com/5818309/83409893-b951a880-a3eb-11ea-847b-2cb82a7b59ae.png)
](https://www.figma.com/proto/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=397%3A1073&scaling=min-zoom)

### Formulário
Título | Descrição | Validações 
--------|---------------|---------------
Código | - | `required`, `unique`
Nome | - | `required`
Descrição | - | -
Prazo | - | `required`, `boolean`
Preço | - | `required`, `numeric`, `min:0`
Exames | - | `required`
Status | - | `required`, `boolean`

## TODO

- [ ] Abir modal de cadastro ao clicar no botão.
- [ ] Formulário
- [ ] Validações
- [ ] Ao clicar em Cadastrar:
  - [ ] Verifica a Validação do formulário
  - [ ] Muda o estado do formulário para loading = true
  - [ ] Envia a requisição
  - [ ] Se Sucesso:Emite evento, limpa o formulário e fecha modal
  - [ ] Se Falha: Notificar Falha
  - [ ] Muda o estado do formulário loading = false
- [ ] Ao Clicar em Cancelar:
  - [ ]  Limpa o Formulário e fecha modal

## Observações e Sugestões

- Adicionar um botão de "Cadastrar e adicionar outro" ou um checkbox que possibilite o usuário a permanecer com a modal aberta e adicionar outros perfis de maneira contínua.
- Adicionar ao formulário o campo/switch para o status, permitindo ao usuário decidir se o exame está ativo/inativo.

**Comment by leolands** [comment]
Legal a estrutura nova @PCiranda

**Comment by leolands** [comment]
Concordo com as observações.
