### ISSUE TITLE
[ Laboratório ] Solicitação de Exames

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#80]
## Objetivo

Proporcionar uma view em que as Clínicas possam solicitar Exames para um determinado Laboratório. 

## Design

[![Solicitação de Exames  Versão com Cards](https://user-images.githubusercontent.com/5818309/83987163-be47b800-a915-11ea-95d4-2097c19378fc.png)
](https://www.figma.com/proto/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=279%3A737&scaling=min-zoom)

### Conteúdo da Lista
Título | Descrição | Filtrável | Classificável
---|---|---|---
Tipo | Exame ou Perfil | Sim | Não 
Código | - | Sim | Sim
Nome | - | Sim | Sim
Descrição | - | Sim | Não
Materiais | - | Não | Não 
Preço | - | Não | Não 
Ações | Adicionar e Expandir | Não | Não

## TODO

- [ ] Lista de Exames e Perfis
  - [ ] Filtrar itens com base no campo Pesquisar
  - [ ] Filtro dedicado aos Tipos: Exames, Perfis ou Ambos
  - [ ] Filtro dedicado às ETIQUETAS.
  - [ ] Expandir um Exame exibe mais detalhes.
  - [ ] Expandir um Perfil exibe os Exames associados.
- [ ] Carrinho
  - [ ] Expandir/Recolher carrinho
  - [ ] O Exame A está presente no carrinho. Ao adicionar o Perfil ABC  (que possui o exame A) este NÃO DEVE ser duplicado. 
  - [ ] Somar os preços e exibir o total.

## Observações e Sugestões

- Em algum momento a Clínica deve determinar para qual laboratório efetuará a solicitação, e então carregaremos os Exames e Perfis com status Ativos deste laboratório selecionado.
- Falta adicionar as _**etiquetas**_ aos itens da lista.
- Devemos permitir selecionar o filtro de Exame e Perfil ao mesmo tempo.
- Se o conjunto de filtros aplicados retornar uma coleção vazia, uma mensagem fixa deve ser apresentada no local da lista

## API
https://dev.hubvet.app/docs#exames-exames
https://dev.hubvet.app/docs#perfis-perfis
Hubvet8/hubvet-api#56
