### ISSUE TITLE
[ Laboratório ] Validação da Solicitação de Exames

### ISSUE THREAD

**Issue by PCiranda** [Hubvet8/hubvet-web#81]
## Objetivo

Exames que possuem Formulário devem ser preenchidos e validados neste etapa.

## Design

[![Solicitação de Exames  Paciente](https://user-images.githubusercontent.com/5818309/83990325-a7a65e80-a91f-11ea-8a76-5262bc14af93.png)
](https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=403%3A2048)

### Conteúdo da Lista
Título | Descrição | Filtrável | Classificável
---|---|---|---
Tipo | Exame ou Perfil | Sim | Não 
Código | - | Sim | Sim
Nome | - | Sim | Sim
Descrição | - | Sim | Não
Materiais | - | Não | Não 
Preço | - | Não | Não 
Ações | Adicionar e Expandir | Não | Não

## TODO

- [ ] Lista de Exames
- [ ] Ao clicar no Exame que o formulário deve ser preenchido uma modal será apresentada.
- [ ] Gerar formulário campos do formulário dinamicamente.
- [ ] O botão de avançar só deve ficar disponível quando todos os formulários estiverem preenchidos e corretamente. 
 
## Observações e Sugestões

- Classificar a lista de maneira que os exames que possuam Formulários e que não foram preenchidos corretamente permaneçam no topo
- Precisamos conversar e definir um schema para os inputs (exemplo o google forms) este mesmo schema poderá ser usado para definição dos inputs do resultados.

atributos | valores
---|---
Label | Login
Descrição | identificador único do usuário.
Chave | login
Tipo | text\number\area\select\range\date\time\file
Validações | "min:6\|max:32\|unique"
Opções | {"chave": "valor" }
multiplos | false

## API
https://dev.hubvet.app/docs#exames-exames
https://dev.hubvet.app/docs#perfis-perfis
Hubvet8/hubvet-api#56
