### ISSUE TITLE
Login de Usuário [Autenticação Interna]

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#9]
## Requisitos
Se faz necessário a criação de uma única interface de login para os usuários acessarem a plataforma.  
Em experiências anteriores quando utilizamos uma tela de login para laboratórios e outra para clientes do laboratório, houveram situações da recepcionista mandar o link de acesso do laboratório para acesso dos clientes, ocasionando erro de login e clientes insatisfeitos.

*User Story*
**US001**: Eu como Médico veterinário gostaria de acessar várias clinicas ou laboratórios credenciados, para que eu possa ter acesso as informações a mim concedidas em um único ambiente.

**Critérios de Aceitação**
O usuário não pode ter dois cadastros distintos com o mesmo e-mail.
Clínicas não efetuam login, somente usuários que pertencem a uma clínica ativa na plataforma.

**Impacto se não desenvolvida**
O projeto será inviabilizado.

**Proporção**
Iremos atingir 100% dos usuários com esta funcionalidade.

**Objetivo**
Proporcionar acesso aos usuários aos ambientes de interação.

**Evidência**
Para que os clientes tenham acesso a plataforma e usufruam das funcionalidades é evidente que precisamos disponibilizar uma interface de acesso.

**Ideias**
Seria interessante entregarmos uma experiência positiva na validação da conta.
Nos preocuparmos com o retorno que a plataforma proporcionará ao usuário, evitando erros em outras línguas, que não a selecionada, e tratando erros com informações "traduzidas" ao usuário.

**Urgência**
Esta funcionalidade precisa estar pronta em 2 dias com todas as requisições abaixo.

## Especificação Técnica
Falta especificação

## Design

![Login.png](https://images.zenhubusercontent.com/5e9a31126a44049a3a9b9e85/e3ad79d7-7764-486e-8210-e47794e05dd0)

https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=87%3A21

## To-do

 - [x] Call para definição
 - [ ] Construir Especificação
 - [x] Design das telas de Login
  1. Login
     - [x] Tela inicial  para autenticação de usuário e senha
     - [x] Link para tela de novo cadastro
     - [x] Link para Ajuda da Plataforma
     - [x] Link para Políticas de Privacidade da Plataforma
     - [x] Link para os termos de uso da Plataforma
     - [ ] Opção para manter o usuário logado até que o mesmo desconecte
 - [ ] Implementação
 - [ ] Teste de usabilidade
 - [ ] Deploy

**Comment by PCiranda** [comment]
O modelo novo de requisição ficou excelente.

Vamos separa a implementação deste em duas etapas:

- Autenticação interna.
- oAuth de terceiros (complementar)

Poderíamos remover a parte da tradução? Mover para uma issue própria, pois ela atinge o sistema como um todo e não somente a "Autenticação do usuário"

**Comment by PCiranda** [comment]
Acredito que o mesmo pode ser feito com o "link para ajuda"

Pode tornar-se uma issue própria com mais detalhamento, como um sistema de faq gerenciado pelo usuário.

**Comment by leolands** [comment]
De acordo. Irei separar essas informações em novas issues

**Comment by leolands** [comment]
@johhny0 Issue atualizada com novo Design.
